/**
 * Copyright (c) 2011 Accenture
 * Licensed under the MIT open source license
 * http://www.opensource.org/licenses/mit-license.php
 */
package no.uka.findmyapp.android.rest.client;

/**
 * The Enum UkappsServices.
 *
 * @author jostein.guldal
 */

public enum UkappsServices {
	/** First thing. */
	
	GET_ALL_FACTS,
	//GET_ALL_USER_LOCATIONS,
	GET_ALL_LOCATIONS,
	//GET_APPSTORE_LIST_FOR_PLATFORM,
	GET_HUMIDITY_DATA,
	GET_EVENTS_ON_PLACE,
	GET_FRIENDS_ATTENDING_EVENT,
	GET_NEXT_UKA_EVENT,
	//GET_LOCATION_OF_FRIENDS,
	GET_NOISE_DATA,
	GET_POSITION_BASED_ON_WLAN_SIGNALS,
	GET_PRIVACY,
	GET_RANDOM_FACT,
	GET_TEMPERATURE_DATA,
	//GET_UKA_EVENTS_TODAY,
	//GET_UKA_EVENTS_TOMORROW,
	//GET_UKA_EVENT_BY_ID,
	//GET_UKA_PROGRAM_START_END_DATE,
	GET_UKA_PROGRAM_FOR_DATE,
	GET_UKA_PROGRAM_PLACES,
	GET_USER_LOCATION,
	GET_USER_COUNT_AT_LOCATION,
	GET_USER_COUNT_AT_ALL_LOCATIONS,
	//GET_USERS_AT_LOCATION,
	//LOCATION_GET_ALL_LOCATIONS,
	//REGISTER_USER_LOCATION,
	//REGISTER_SAMPLE,
	//SEARCH_FOR_UKA_PROGRAM_BY_NAME,
	SET_TEMPERATURE_DATA,
	UKAEVENTS;
}